const CLIENTS = [
  {
    id: "CLIENT-1",
    clientName: "Georgi",
    clinicianName: "Georgia Smith",
    clientType: "INDIVIDUAL",
    treatmentPlan: "Not saved",
    lastSession: "2024-11-19T19:42:16.912Z",
    unsavedNotes: "3213",
  },
  {
    id: "CLIENT-2",
    clientName: "Ivan",
    clinicianName: "Ivan Ivanov",
    clientType: "COUPLE",
    treatmentPlan: "Not saved",
    lastSession: "2023-11-19T19:42:16.912Z",
    unsavedNotes: "3213",
  },
  {
    id: "CLIENT-3",
    clientName: "Petar",
    clinicianName: "Petar Petrov",
    clientType: "FAMILY",
    treatmentPlan: "Not saved",
    lastSession: "2022-11-19T19:42:16.912Z",
    unsavedNotes: "3213",
  },
  {
    id: "CLIENT-4",
    clientName: "Stefan",
    clinicianName: "Stefan Stoyanov",
    clientType: "CHILD",
    treatmentPlan: "Not saved",
    lastSession: "2021-11-19T19:42:16.912Z",
    unsavedNotes: "3213",
  },
  {
    id: "CLIENT-5",
    clientName: "Vasil",
    clinicianName: "Vasil Vasilev",
    clientType: "GROUP",
    treatmentPlan: "Not saved",
    lastSession: "2020-11-19T19:42:16.912Z",
    unsavedNotes: "3213",
  },
  {
    id: "CLIENT-6",
    clientName: "Zdravko",
    clinicianName: "Zdravko Zdravkov",
    clientType: "INDIVIDUAL",
    treatmentPlan: "Not saved",
    lastSession: "2019-11-19T19:42:16.912Z",
    unsavedNotes: "3213",
  },
  {
    id: "CLIENT-7",
    clientName: "Atanas",
    clinicianName: "Atanas Atanasov",
    clientType: "COUPLE",
    treatmentPlan: "Not saved",
    lastSession: "2018-11-19T19:42:16.912Z",
    unsavedNotes: "3213",
  },
  {
    id: "CLIENT-8",
    clientName: "Borislav",
    clinicianName: "Borislav Borisov",
    clientType: "FAMILY",
    treatmentPlan: "Not saved",
    lastSession: "2017-11-19T19:42:16.912Z",
    unsavedNotes: "3213",
  },
  {
    id: "CLIENT-9",
    clientName: "Vladimir",
    clinicianName: "Vladimir Vladimirov",
    clientType: "CHILD",
    treatmentPlan: "Not saved",
    lastSession: "2016-11-19T19:42:16.912Z",
    unsavedNotes: "3213",
  },
  {
    id: "CLIENT-10",
    clientName: "Gosho",
    clinicianName: "Gosho Goshev",
    clientType: "GROUP",
    treatmentPlan: "Not saved",
    lastSession: "2015-11-19T19:42:16.912Z",
    unsavedNotes: "3213",
  },
  {
    id: "CLIENT-11",
    clientName: "Ivan",
    clinicianName: "Ivan Ivanov",
    clientType: "INDIVIDUAL",
    treatmentPlan: "Not saved",
    lastSession: "2014-11-19T19:42:16.912Z",
    unsavedNotes: "3213",
  },
  {
    id: "CLIENT-12",
    clientName: "Petar",
    clinicianName: "Petar Petrov",
    clientType: "COUPLE",
    treatmentPlan: "Not saved",
    lastSession: "2013-11-19T19:42:16.912Z",
    unsavedNotes: "3213",
  },
  {
    id: "CLIENT-13",
    clientName: "Stefan",
    clinicianName: "Stefan Stoyanov",
    clientType: "FAMILY",
    treatmentPlan: "Not saved",
    lastSession: "2012-11-19T19:42:16.912Z",
    unsavedNotes: "3213",
  },
  {
    id: "CLIENT-14",
    clientName: "Vasil",
    clinicianName: "Vasil Vasilev",
    clientType: "CHILD",
    treatmentPlan: "Not saved",
    lastSession: "2011-11-19T19:42:16.912Z",
    unsavedNotes: "3213",
  },
  {
    id: "CLIENT-15",
    clientName: "Zdravko",
    clinicianName: "Zdravko Zdravkov",
    clientType: "GROUP",
    treatmentPlan: "Not saved",
    lastSession: "2010-11-19T19:42:16.912Z",
    unsavedNotes: "3213",
  }
];

export { CLIENTS };
