const CLIENTS = [
  {
    id: "CLIENT-1",
    clientName: "Georgi",
    clinicianName: "Georgia Smith",
    clientType: "INDIVIDUAL",
    treatmentPlan: "Not saved",
    lastSession: "2024-11-19T19:42:16.912Z",
    unsavedNotes: "3213",
    status: true,
  },
  {
    id: "CLIENT-2",
    clientName: "Ivan",
    clinicianName: "Ivan Ivanov",
    clientType: "COUPLE",
    treatmentPlan: "Not saved",
    lastSession: "2023-11-19T19:42:16.912Z",
    unsavedNotes: "3213",
    status: true,
  },
  {
    id: "CLIENT-3",
    clientName: "Petar",
    clinicianName: "Petar Petrov",
    clientType: "INDIVIDUAL",
    treatmentPlan: "Not saved",
    lastSession: "2022-11-19T19:42:16.912Z",
    unsavedNotes: "3213",
    status: true,
  },
  {
    id: "CLIENT-4",
    clientName: "Stefan",
    clinicianName: "Stefan Stoyanov",
    clientType: "COUPLE",
    treatmentPlan: "Not saved",
    lastSession: "2021-11-19T19:42:16.912Z",
    unsavedNotes: "3213",
    status: true,
  },
  {
    id: "CLIENT-5",
    clientName: "Vasil",
    clinicianName: "Vasil Vasilev",
    clientType: "FAMILY",
    treatmentPlan: "Not saved",
    lastSession: "2020-11-19T19:42:16.912Z",
    unsavedNotes: "3213",
    status: true,
  },
  {
    id: "CLIENT-6",
    clientName: "Zdravko",
    clinicianName: "Zdravko Zdravkov",
    clientType: "CHILD",
    treatmentPlan: "Not saved",
    lastSession: "2019-11-19T19:42:16.912Z",
    unsavedNotes: "3213",
    status: true,
  },
  {
    id: "CLIENT-7",
    clientName: "Atanas",
    clinicianName: "Atanas Atanasov",
    clientType: "GROUP",
    treatmentPlan: "Not saved",
    lastSession: "2018-11-19T19:42:16.912Z",
    unsavedNotes: "3213",
    status: true,
  },
  {
    id: "CLIENT-8",
    clientName: "Borislav",
    clinicianName: "Borislav Borisov",
    clientType: "FAMILY",
    treatmentPlan: "Not saved",
    lastSession: "2017-11-19T19:42:16.912Z",
    unsavedNotes: "3213",
    status: true,
  },
  {
    id: "CLIENT-9",
    clientName: "Vladimir",
    clinicianName: "Vladimir Vladimirov",
    clientType: "CHILD",
    treatmentPlan: "Not saved",
    lastSession: "2016-11-19T19:42:16.912Z",
    unsavedNotes: "3213",
    status: true,
  },
  {
    id: "CLIENT-10",
    clientName: "Gosho",
    clinicianName: "Gosho Goshev",
    clientType: "GROUP",
    treatmentPlan: "Not saved",
    lastSession: "2015-11-19T19:42:16.912Z",
    unsavedNotes: "3213",
    status: true,
  },
  {
    id: "CLIENT-11",
    clientName: "Alice",
    clinicianName: "Alice Smith",
    clientType: "INDIVIDUAL",
    treatmentPlan: "Not saved",
    lastSession: "2014-11-19T19:42:16.912Z",
    unsavedNotes: "3213",
    status: true,
  },
  {
    id: "CLIENT-12",
    clientName: "Bob",
    clinicianName: "Bob Bobov",
    clientType: "COUPLE",
    treatmentPlan: "Not saved",
    lastSession: "2013-11-19T19:42:16.912Z",
    unsavedNotes: "3213",
    status: true,
  },
  {
    id: "CLIENT-13",
    clientName: "Charlie",
    clinicianName: "Charlie Brown",
    clientType: "FAMILY",
    treatmentPlan: "Not saved",
    lastSession: "2012-11-19T19:42:16.912Z",
    unsavedNotes: "3213",
    status: true,
  },
  {
    id: "CLIENT-14",
    clientName: "Dimitar",
    clinicianName: "Dimitar Dimitrov",
    clientType: "CHILD",
    treatmentPlan: "Not saved",
    lastSession: "2011-11-19T19:42:16.912Z",
    unsavedNotes: "3213",
    status: true,
  },
  {
    id: "CLIENT-15",
    clientName: "Emil",
    clinicianName: "Emil Emilov",
    clientType: "GROUP",
    treatmentPlan: "Not saved",
    lastSession: "2010-11-19T19:42:16.912Z",
    unsavedNotes: "3213",
    status: true,
  },
  {
    id: "CLIENT-16",
    clientName: "Fedor",
    clinicianName: "Fedor Fedorov",
    clientType: "INDIVIDUAL",
    treatmentPlan: "Not saved",
    lastSession: "2009-11-19T19:42:16.912Z",
    unsavedNotes: "3213",
    status: true,
  },
  {
    id: "CLIENT-17",
    clientName: "Georgi",
    clinicianName: "Georgia Clark",
    clientType: "COUPLE",
    treatmentPlan: "Not saved",
    lastSession: "2008-11-19T19:42:16.912Z",
    unsavedNotes: "3213",
    status: true,
  },
  {
    id: "CLIENT-18",
    clientName: "Hristo",
    clinicianName: "Hristo Hristov",
    clientType: "INDIVIDUAL",
    treatmentPlan: "Not saved",
    lastSession: "2007-11-19T19:42:16.912Z",
    unsavedNotes: "3213",
    status: true,
  },
  {
    id: "CLIENT-19",
    clientName: "Ixvar",
    clinicianName: "Ixvar Ixvarov",
    clientType: "GROUP",
    treatmentPlan: "Not saved",
    lastSession: "2006-11-19T19:42:16.912Z",
    unsavedNotes: "3213",
    status: true,
  },
  {
    id: "CLIENT-20",
    clientName: "Joro",
    clinicianName: "Joro Jorov",
    clientType: "CHILD",
    treatmentPlan: "Not saved",
    lastSession: "2005-11-19T19:42:16.912Z",
    unsavedNotes: "3213",
    status: true,
  },
  {
    id: "CLIENT-21",
    clientName: "Kalin",
    clinicianName: "Kalin Kalinov",
    clientType: "COUPLE",
    treatmentPlan: "Not saved",
    lastSession: "2004-11-19T19:42:16.912Z",
    unsavedNotes: "3213",
    status: false,
  },
  {
    id: "CLIENT-22",
    clientName: "Lazar",
    clinicianName: "Lazar Lazarov",
    clientType: "FAMILY",
    treatmentPlan: "Not saved",
    lastSession: "2003-11-19T19:42:16.912Z",
    unsavedNotes: "3213",
    status: false,
  },
  {
    id: "CLIENT-23",
    clientName: "Mihail",
    clinicianName: "Mihail Mihailov",
    clientType: "CHILD",
    treatmentPlan: "Not saved",
    lastSession: "2002-11-19T19:42:16.912Z",
    unsavedNotes: "3213",
    status: false,
  },
  {
    id: "CLIENT-24",
    clientName: "Nikolay",
    clinicianName: "Nikolay Nikolov",
    clientType: "GROUP",
    treatmentPlan: "Not saved",
    lastSession: "2001-11-19T19:42:16.912Z",
    unsavedNotes: "3213",
    status: false,
  },
  {
    id: "CLIENT-25",
    clientName: "Ognian",
    clinicianName: "Ognian Ognianov",
    clientType: "GROUP",
    treatmentPlan: "Not saved",
    lastSession: "2000-11-19T19:42:16.912Z",
    unsavedNotes: "3213",
    status: false,
  },
  {
    id: "CLIENT-26",
    clientName: "Pvanko",
    clinicianName: "Pvanko Pvankov",
    clientType: "COUPLE",
    treatmentPlan: "Not saved",
    lastSession: "1999-11-19T19:42:16.912Z",
    unsavedNotes: "3213",
    status: false,
  },
  {
    id: "CLIENT-27",
    clientName: "Qnko",
    clinicianName: "Qnko Qnkov",
    clientType: "INDIVIDUAL",
    treatmentPlan: "Not saved",
    lastSession: "1998-11-19T19:42:16.912Z",
    unsavedNotes: "3213",
    status: false,
  },
  {
    id: "CLIENT-28",
    clientName: "Rosen",
    clinicianName: "Rosen Rosenov",
    clientType: "GROUP",
    treatmentPlan: "Not saved",
    lastSession: "1997-11-19T19:42:16.912Z",
    unsavedNotes: "3213",
    status: false,
  },
  {
    id: "CLIENT-29",
    clientName: "Simeon",
    clinicianName: "Simeon Simeonov",
    clientType: "FAMILY",
    treatmentPlan: "Not saved",
    lastSession: "1996-11-19T19:42:16.912Z",
    unsavedNotes: "3213",
    status: false,
  },
  {
    id: "CLIENT-30",
    clientName: "Todor",
    clinicianName: "Todor Todorov",
    clientType: "CHILD",
    treatmentPlan: "Not saved",
    lastSession: "1995-11-19T19:42:16.912Z",
    unsavedNotes: "3213",
    status: false,
  },
];

export { CLIENTS };
